### ISSUE TITLE
Crashes on 4.2-dev5_mono when using graph

### ISSUE THREAD

**Issue by Invertex** [Ericdowney/SignalVisualizer#3]
**Describe the bug**
Editor instantly crashes when doing something as simple as "Clear Graph" or any other operation.
Console closes and no output log to diagnose.

**To Reproduce**
1. Open project in 4.2 dev5 mono
2. Click "Clear Graph"
3. Interact with the graph.
4. Crash

**Expected behavior**
Graph should work and not crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Godot Version [e.g. 4.2-dev5_mono]

**Additional context**
N/A

**Comment by Ericdowney** [comment]
@Invertex Apologies for taking so long on this. I just pushed a new version (0c3adabc8a0c84d5a9238331101723c45266c461) and created a new release `Release v1.2.1`. This should fix the issue and be backwards compatible with other 4.x versions of Godot.

**Comment by Invertex** [comment]
Thanks for the update! No worries!

I am curious, as someone new to Godot development, how exactly do you go about diagnosing an issue like this for Godot? I couldn't get an error log so felt a bit stuck. Or are you attaching a debugger to Godot to try and get more info?

Cheers

**Comment by Ericdowney** [comment]
I'm still relatively new to Godot myself. 😅 I'm not aware of any debugging that can be done with plugins since the debugger runs in the same process as the engine. In this case, your comment helped the most. The issue was with `Clear Graph` which runs on every clear and generate call. 

> Or are you attaching a debugger to Godot to try and get more info?

I never thought about doing ☝️ , but I might give it a try.
